title: CSA Content Standards
description: Reference documentation for the Content Scaling Agent
theme: jekyll-theme-cayman
baseurl: "/csa-content-standards"
url: "https://piercewilliams.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
